version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PORT=8000
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   restart: unless-stopped

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared
  #   command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
  #   restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    ports:
      - "3123:3000"
    environment:
      - PORT=3000
    # volumes:
    #   - ./frontend:/app
    # depends_on:
    #   - backend
    # restart: unless-stopped