services:
  backend:
    container_name: backend
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env.production
    ports:
      - 8000:8000

  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3123:3000"
  #   environment:
  #     - PORT=3000
  #   depends_on:
  #     - backend
  #   restart: unless-stopped
